@autor: Daniel Andrés Dávila Lesmes
@Codigo: 20161015108
@Asignatura: Introducción a la Ciencia de datos 2021-3
@Correo: dadavilal@correo.udistrital.edu.co

In [1]:
import numpy as np

**Ejercicio con arreglos**

Generar un arreglo tridimensional de tamaño 9x9x9 con los números enteros del 0 al 728.

In [2]:
arregloInicial=np.arange(729).reshape(9,9,9)
arregloInicial

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
        [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59,  60,  61,  62],
        [ 63,  64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98],
        [ 99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116],
        [117, 118, 119, 120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151, 152],
        [153, 154, 155, 156, 157, 158, 159, 160, 161]],

      

Imaginar que el arreglo se divide en 27 arreglos de 3x3x3

In [4]:
arregloAjustado=np.resize(arregloInicial,(27,3,3,3))
print("Número de elementos:",len(arregloAjustado))
arregloAjustado

Número de elementos: 27


array([[[[  0,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8]],

        [[  9,  10,  11],
         [ 12,  13,  14],
         [ 15,  16,  17]],

        [[ 18,  19,  20],
         [ 21,  22,  23],
         [ 24,  25,  26]]],


       [[[ 27,  28,  29],
         [ 30,  31,  32],
         [ 33,  34,  35]],

        [[ 36,  37,  38],
         [ 39,  40,  41],
         [ 42,  43,  44]],

        [[ 45,  46,  47],
         [ 48,  49,  50],
         [ 51,  52,  53]]],


       [[[ 54,  55,  56],
         [ 57,  58,  59],
         [ 60,  61,  62]],

        [[ 63,  64,  65],
         [ 66,  67,  68],
         [ 69,  70,  71]],

        [[ 72,  73,  74],
         [ 75,  76,  77],
         [ 78,  79,  80]]],


       [[[ 81,  82,  83],
         [ 84,  85,  86],
         [ 87,  88,  89]],

        [[ 90,  91,  92],
         [ 93,  94,  95],
         [ 96,  97,  98]],

        [[ 99, 100, 101],
         [102, 103, 104],
         [105, 106, 107]]],


       [[[108, 109, 110],
      

desarrollar una función que permita intercambiar la posición de dos de estos bloques, pasándole como argumento únicamente la identificación de los bloques a intercambiar (los bloques se deben identificar con números del 0 al 26)


In [5]:
#Función para intercambiar elementos de un arreglo de una posición a otra
#Parámetros:
#arreglo: matriz de n dimensiones
#index1: posición del primer elemento a intercambiar
#index1: posición del segundo elemento a intercambiar
def intercambio(arreglo,index1,index2):
    matriz=arreglo.copy()
    elemento1=arreglo[index1][:]
    elemento2=arreglo[index2][:]
    print("-----------------------------------------------")
    print("Elementos a intercambiar:\n")
    print(f"Elemento1 en el índice {index1}\n{elemento1},\n intercambia con Elemento2 en el indice {index2}\n{elemento2}")
    print("-----------------------------------------------")
    matriz[index2][:]=elemento1[:]
    matriz[index1][:]=elemento2[:]
    return matriz

Intercambiar elementos 

In [7]:
index1=0
index2=1
print(f"Se intecrambian los elementos de la posicion{index1} y posicion {index2}")
arregloIntercambio=intercambio(arregloAjustado,index1,index2)
arregloIntercambio

Se intecrambian los elementos de la posicion0 y posicion 1
-----------------------------------------------
Elementos a intercambiar:

Elemento1 en el índice 0
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]],
 intercambia con Elemento2 en el indice 1
[[[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]]]
-----------------------------------------------


array([[[[ 27,  28,  29],
         [ 30,  31,  32],
         [ 33,  34,  35]],

        [[ 36,  37,  38],
         [ 39,  40,  41],
         [ 42,  43,  44]],

        [[ 45,  46,  47],
         [ 48,  49,  50],
         [ 51,  52,  53]]],


       [[[  0,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8]],

        [[  9,  10,  11],
         [ 12,  13,  14],
         [ 15,  16,  17]],

        [[ 18,  19,  20],
         [ 21,  22,  23],
         [ 24,  25,  26]]],


       [[[ 54,  55,  56],
         [ 57,  58,  59],
         [ 60,  61,  62]],

        [[ 63,  64,  65],
         [ 66,  67,  68],
         [ 69,  70,  71]],

        [[ 72,  73,  74],
         [ 75,  76,  77],
         [ 78,  79,  80]]],


       [[[ 81,  82,  83],
         [ 84,  85,  86],
         [ 87,  88,  89]],

        [[ 90,  91,  92],
         [ 93,  94,  95],
         [ 96,  97,  98]],

        [[ 99, 100, 101],
         [102, 103, 104],
         [105, 106, 107]]],


       [[[108, 109, 110],
      